CREATE TABLESPACE WAR3SHOP
    DATAFILE 'war3shop.dbf' 
    SIZE 1024M 
    AUTOEXTEND ON NEXT 128M 
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL;

CREATE TEMPORARY TABLESPACE WAR3SHOP_TEMP 
    TEMPFILE 'war3shop-temp.dbf' 
    SIZE 1024M 
    AUTOEXTEND ON NEXT 128M 
    MAXSIZE UNLIMITED
    EXTENT MANAGEMENT LOCAL;
    
CREATE USER WAR3SHOP
    IDENTIFIED BY 123
    DEFAULT TABLESPACE WAR3SHOP
    TEMPORARY TABLESPACE WAR3SHOP_TEMP;
    
GRANT CONNECT, RESOURCE TO WAR3SHOP;
